apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 --file ./docker-compose.yml
      convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: tvapp
  name: tvapp
spec:
  ports:
  - name: "9999"
    port: 9999
    targetPort: 9999
  selector:
    io.kompose.service: tvapp
status:
  loadBalancer: {}
